{
 "title": "IaaS - VM - Storage Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "subscription",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "resourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "VM",
    "label": "Virtual Machine",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "VM Disk(s)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OS Disk",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "Resources\r\n| where type == \"microsoft.compute/virtualmachines\"\r\n| where name == \"$VM\"\r\n| where resourceGroup == \"$resourceGroup\"\r\n| where subscriptionId == \"$subscription\"\r\n| project \r\nosDiskname          = properties.storageProfile.osDisk.name, \r\ndiskSizeGB          = properties.storageProfile.osDisk.diskSizeGB, \r\ncaching             = properties.storageProfile.osDisk.caching,\r\nosDiskId            = tolower(tostring(properties.storageProfile.osDisk.managedDisk.id))\r\n| join kind=leftouter (\r\n Resources \r\n | where type =~ 'microsoft.compute/disks'\r\n | extend osDiskId=tolower(tostring(id))\r\n | where properties !has 'Unattached'\r\n | where properties has 'osType'\r\n | project \r\n diskMBpsReadWrite = properties.diskMBpsReadWrite,\r\n diskIOPSReadWrite = properties.diskIOPSReadWrite,\r\n osType = properties.osType,\r\n tier = properties.tier,\r\n sku = sku.name,\r\n osDiskId\r\n) on $left.osDiskId == $right.osDiskId\r\n| project osDiskId, osType, diskSizeGB, tier, sku, diskIOPSReadWrite, diskMBpsReadWrite, caching"
     },
     "subscriptions": [ "$subscription" ]
    }
   ]
  },
  {
   "title": "Data Disks",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "Resources \r\n| where type == \"microsoft.compute/virtualmachines\"\r\n| where name == \"$VM\"\r\n| where subscriptionId == \"$subscription\"\r\n| where resourceGroup == \"$resourceGroup\"\r\n| mv-expand dataDisk=properties.storageProfile.dataDisks\r\n| extend diskId = tolower(tostring(dataDisk.managedDisk.id))\r\n| extend diskName          = dataDisk.name\r\n| extend diskSizeGB  = dataDisk.diskSizeGB\r\n| extend diskCaching             = dataDisk.caching\r\n| extend diskLun = toint(dataDisk.lun)\r\n| extend diskWriteAcceleratorEnabled = dataDisk.writeAcceleratorEnabled\r\n | join kind=leftouter (\r\n Resources \r\n | where type =~ 'microsoft.compute/disks'\r\n | where properties !has \"osType\"\r\n | where properties !has 'Unattached'\r\n | extend diskId=tolower(tostring(id))\r\n | extend diskIOPSReadWrite=properties.diskIOPSReadWrite\r\n | extend diskMBpsReadWrite=properties.diskMBpsReadWrite\r\n | extend tier=properties.tier\r\n | extend encryption=properties.encryption.type\r\n | extend skuName=sku.name\r\n ) on diskId\r\n | project lun=diskLun, diskId, sizeGB=diskSizeGB, tier, sku=skuName, diskIOPSReadWrite, diskMBpsReadWrite, caching=diskCaching, writeAcceleratorEnabled=diskWriteAcceleratorEnabled, encryption\r\n | order by lun asc"
     },
     "subscriptions": [ "$subscription" ]
    }
   ]
  },
  { "title": "All Disks - IO/Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Disk Read Bytes/Sec",
   "type": "timeseries",
   "description": "The number of total bytes that are read in a second from all disks attached to a VM.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Read Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Disk Read Operations/Sec",
   "type": "timeseries",
   "description": "The number of input operations that are read in a second from all disks attached to a VM.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Read Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Disk Write Bytes/Sec",
   "type": "timeseries",
   "description": "The number of bytes that are written in a second from all disks attached to a VM.",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Write Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Disk Write Operations/Sec",
   "type": "timeseries",
   "description": "The number of output operations that are written in a second from all disks attached to a VM.",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Write Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "OS Disk - IO/Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "OS Disk Read Bytes/Sec",
   "type": "timeseries",
   "description": "The number of bytes that are read in a second from the OS disk.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 19 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Read Bytes/sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "OS Disk Read Operations/Sec",
   "type": "timeseries",
   "description": "The number of input operations that are read in a second from the OS disk.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 19 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Read Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "OS Disk Write Bytes/Sec",
   "type": "timeseries",
   "description": "The number of bytes that are written in a second from the OS disk.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 19 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Write Bytes/sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "OS Disk Write Operations/Sec",
   "type": "timeseries",
   "description": "The number of output operations that are written in a second from the OS disk.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 19 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Write Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "OS Disk Queue Depth",
   "type": "timeseries",
   "description": "The number of current outstanding IO requests that are waiting to be read from or written to the OS disk.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Queue Depth",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "Data Disk - IO/Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Data Disk Read Bytes/Sec",
   "type": "timeseries",
   "description": "The number of bytes that are read in a second from the data disk(s).",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Read Bytes/sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk Read Operations/Sec",
   "type": "timeseries",
   "description": "The number of input operations that are read in a second from data disk(s).",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Read Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk Write Bytes/Sec",
   "type": "timeseries",
   "description": "The number of bytes that are written in a second from the data disk(s).",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Write Bytes/sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk Write Operations/Sec",
   "type": "timeseries",
   "description": "The number of output operations that are written in a second from data disk(s).",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Write Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk Queue Depth",
   "type": "timeseries",
   "description": "The number of current outstanding IO requests that are waiting to be read from or written to the data disk(s).",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Queue Depth",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "VM Capping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "VM Cached IOPS Consumed Percentage",
   "type": "timeseries",
   "description": "The percentage calculated by the total IOPS completed over the max cached virtual machine IOPS limit. If this amount is at 100%, your application running is IO capped from your VM's cached IOPS limit.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "VM Cached IOPS Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "VM Cached Bandwidth Consumed Percentage",
   "type": "timeseries",
   "description": "The percentage calculated by the total disk throughput completed over the max cached virtual machine throughput. If this amount is at 100%, your application running is IO capped from your VM's cached bandwidth limit.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "VM Cached Bandwidth Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "VM Uncached IOPS Consumed Percentage",
   "type": "timeseries",
   "description": "The percentage calculated by the total IOPS on a virtual machine completed over the max uncached virtual machine IOPS limit. If this amount is at 100%, your application running is IO capped from your VM's uncached IOPS limit.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "VM Uncached IOPS Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "VM Uncached Bandwidth Consumed Percentage",
   "type": "timeseries",
   "description": "The percentage calculated by the total disk throughput on a virtual machine completed over the max provisioned virtual machine throughput. If this amount is at 100%, your application running is IO capped from your VM's uncached bandwidth limit.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "VM Uncached Bandwidth Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "Disk capping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "OS Disk IOPS Consumed Percentage",
   "type": "timeseries",
   "description": "The percentage calculated by the OS disk IOPS completed over the provisioned OS disk IOPS. If this amount is at 100%, your application running is IO capped from your OS disk's IOPS limit.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk IOPS Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "OS Disk Bandwidth Consumed Percentage",
   "type": "timeseries",
   "description": "The percentage calculated by the OS disk throughput completed over the provisioned OS disk throughput. If this amount is at 100%, your application running is IO capped from your OS disk's bandwidth limit.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Bandwidth Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk IOPS Consumed Percentage",
   "type": "timeseries",
   "description": "The percentage calculated by the data disk IOPS completed over the provisioned data disk IOPS. If this amount is at 100%, your application running is IO capped from your data disk's IOPS limit.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk IOPS Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk Bandwidth Consumed Percentage",
   "type": "timeseries",
   "description": "The percentage calculated by the data disk throughput completed over the provisioned data disk throughput. If this amount is at 100%, your application running is IO capped from your data disk's bandwidth limit.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Bandwidth Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "VM-level Bursting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "VM Cached Used Burst IO Credits Percentage",
   "type": "timeseries",
   "description": "The accumulated percentage of the VM’s cached IOPS burst used. Emitted on a 5 minute interval.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "VM Local Used Burst IO Credits Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "VM Cached Used Burst BPS Credits Percentage",
   "type": "timeseries",
   "description": "The accumulated percentage of the VM’s cached IOPS burst used. Emitted on a 5 minute interval.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "VM Local Used Burst BPS Credits Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "VM Uncached Used Burst IO Credits Percentage",
   "type": "timeseries",
   "description": "The accumulated percentage of the VM’s uncached IOPS burst used. Emitted on a 5 minute interval.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 51 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "VM Remote Used Burst IO Credits Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "VM Uncached Used Burst BPS Credits Percentage",
   "type": "timeseries",
   "description": "The accumulated percentage of the VM’s uncached throughput burst used. Emitted on a 5 minute interval.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "VM Remote Used Burst BPS Credits Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "Disk-level Bursting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "OS Disk Used Burst IO Credits Percentage",
   "type": "timeseries",
   "description": "The accumulated percentage of the IOPS burst used for the OS disk. Emitted on a 5 minute interval.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 59 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Used Burst IO Credits Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "OS Disk Used Burst BPS Credits Percentage",
   "type": "timeseries",
   "description": "The accumulated percentage of the throughput burst used for the OS disk. Emitted on a 5 minute interval.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 59 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Used Burst BPS Credits Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk Used Burst IO Credits Percentage",
   "type": "timeseries",
   "description": "The accumulated percentage of the IOPS burst used for the data disk(s). Emitted on a 5 minute interval.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 59 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Used Burst BPS Credits Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk Used Burst BPS Credits Percentage",
   "type": "timeseries",
   "description": "The accumulated percentage of the throughput burst used for the data disk(s). Emitted on a 5 minute interval.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 59 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Used Burst BPS Credits Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "Disks Target IOPS/Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "OS Disk Target IOPS",
   "type": "timeseries",
   "description": "The IOPS limit that the data disk(s) can achieve without bursting.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Target IOPS",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "OS Disk Target Bandwidth",
   "type": "timeseries",
   "description": "The throughput limit that the OS disk can achieve without bursting.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 67 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Target Bandwidth",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk Target IOPS",
   "type": "timeseries",
   "description": "The IOPS limit that the data disk(s) can achieve without bursting.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 67 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Target IOPS",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk Target Bandwidth",
   "type": "timeseries",
   "description": "The throughput limit that the data(s) disk can achieve without bursting.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 67 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Target Bandwidth",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Disks Max Burst IOPS/Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 }
  },
  {
   "title": "OS Disk Max Burst IOPS",
   "type": "timeseries",
   "description": "The IOPS limit that the OS disk can burst up to.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 75 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Max Burst IOPS",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "OS Disk Max Burst Bandwidth",
   "type": "timeseries",
   "description": "The throughput limit that the OS disk can burst up to.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 75 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Max Burst Bandwidth",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk Max Burst IOPS",
   "type": "timeseries",
   "description": "The IOPS limit that the data disk(s) can burst up to.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 75 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Max Burst IOPS",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Data Disk Max Burst Bandwidth",
   "type": "timeseries",
   "description": "The throughput limit that the data disk(s) can burst up to",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 75 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "LUN",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Data Disk Max Burst Bandwidth",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resourceGroup": "$resourceGroup",
      "resourceName": "$VM",
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  }
 ]
}